routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

    Auth::routes(['verify' => true]);

    Route::group(['middleware'=>['isAdmin','verified'],'prefix'=>'admin','namespace'=>'Admin'],function(){
        Route::get('', 'AdminController@index')->name('admin');
        Route::get('posts/all','PostController@all')->name('posts.all');
        Route::post('posts/move/{post}
        ','PostController@move')->name('posts.move');
        Route::get('category/posts/{id}','CategoryController@posts')->name('category.posts');
       Route::resource('users', 'UserController')->middleware('admin_only');
       Route::resource('posts', 'PostController');
       Route::resource('category', 'CategoryController');
    });
//for user
    Route::group(['middleware'=>['user','verified']],function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::match(['get','post'],'/images', 'HomeController@images')->name('images');
        Route::get('openimage','HomeController@openimage');
        Route::name('cut')->match(['get','post'],'/cut', 'HomeController@cut');
        Route::post('messages','MessageController@index');
        Route::view('/messages', 'user\message');
        Route::post('messages/get','MessageController@getMessage');

    });
    Route::get('posts/{user}', 'PostsForAllController@posts')->name('home.posts');
    Route::post('posts/search', 'PostsForAllController@search')->name('searched.posts');
    Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
    Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
    Route::get('post/{userid}','PostsForAllController@show_post')->name('home.show');
    Route::post('post/store','PostsForAllController@store')->name('home.store');

/*
Route::get('test', function () {
    event(new App\Events\StatusLiked('Someone'));
    return "Event has been sent!";
});*/

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable =['name','description'];
    public function posts() {
        return $this->belongsToMany('App\Post');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Category;
use App\Post;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(Request $request)
    {
        //baci categoriayi posteric urish tex moderator@ u user@ chen mtnum posti jamanak midlevare chi ashxatum
        $this->middleware('admin_only', ['except' => ['posts']]);
    }
    public function index()
    {
        return view('admin.category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.store');
    }
    public function posts($id) {
        $posts = Category::find($id)->posts()->get();
        return view('admin.category.post',compact('posts'));
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required',
            'description'=>'required'
        ]);

        Category::create($request->all());
        return view('admin.category.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data=Category::findorFail($id);
        return view('admin.category.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Category::findorFail($id);
        $data->update($request->all());
        return view('admin.category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Category::findorFail($id);
        $data->posts()->delete();
        $data->delete();
        return view('admin.category.index');
    }
}

resources/views/admin/category/edit.blade.php
@extends('layouts.app')
@section ('content')

    <div class="col-md-8">
        {{--{{Breadcrumbs::render('products',$data->name,'Products')}}--}}

        <div class="card">
            <div class="card-header">Change Category</div> <div class="card-body">
                <form method="POST" action="{{route('category.update',$data->id)}}">
                    @method('PUT')
                    @csrf
                    <div class="form-group row">
                        <label for="name" class="col-sm-4 col-form-label text-md-right"> Name</label>
                        <div class="col-md-6"><input id="name" type="text" name="name" value="{{$data->name}}" required="required" autofocus="autofocus" class="form-control"></div>
                    </div>
                    <div class="form-group row">
                        <label for="text" class="col-md-4 col-form-label text-md-right">Description</label>
                        <div class="col-md-6"><textarea id="password"  name="description" class="form-control">{{$data->description}}</textarea>
                        </div>
                    </div>

                    <div class="form-group row mt-2"><div class="col-md-8 offset-md-4"><button type="submit" class="btn btn-primary">
                                Change
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/category/index.blade.php
@extends('layouts.app')
@section ('content')
    <div><a href="{{route('category.create')}}" class="btn btn-primary">add</a></div>
    <div class="container">
        <h3 class="text-center">Categories</h3>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <table class="table mt-3 jquery_table"  >
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Action</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach(App\Category::all() as $item)
                        <tr>
                            <td><a href="{{route('category.posts',['id'=>$item->id])}}"> {{ $item->name}}</a> </td>
                            <td>{{ $item->description }}</td>
                            <td>

                                <form method ='GET' action="{{route('category.edit',['id'=>$item->id])}}"class="d-inline-block" >
                                    @csrf
                                    <button class="btn btn-primary" type ='submit'> Edit</button> </form></td>
                            <td>
                                <form method ='POST'
                                      action="{{route('category.destroy',['id'=>$item->id])}}" class="d-inline-block ml-2" onclick="return confirm('Are you sure you want to delete this item?')">
                                    @method('DELETE')
                                    @csrf
                                    <button class="btn btn-primary ml-2" type ='submit'>Delete </button>
                                </form>
                            </td>

                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/category/post.blade.php
@extends('layouts.app')
@section ('content')

    <div class="container">
        <h3 class="text-center">Posts</h3>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <table class="table mt-3 jquery_table"  >
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Post</th>
                        <th>Action</th>
                        <th>Action</th>

                    </tr>
                    </thead>
                    <tbody>

                    @foreach($posts->where('moved',0) as $item)
                        <tr>
                            <td>{{ $item->name}} </td>
                            <td>{{ $item->Post }}</td>
                            <td>

                                <form method ='GET' action="{{route('posts.edit',['id'=>$item->id])}}"class="d-inline-block" >
                                    @csrf
                                    <button class="btn btn-primary" type ='submit'> Edit</button> </form></td>
                            <td>
                                <form method ='POST'
                                      action="{{route('posts.destroy',['id'=>$item->id])}}" class="d-inline-block ml-2" onclick="return confirm('Are you sure you want to delete this item?')">
                                    @method('DELETE')
                                    @csrf
                                    <button class="btn btn-primary ml-2" type ='submit'>Delete </button>
                                </form>
                            </td>
                           {{-- <td>
                                <form method ='POST' action="{{route('posts.move',['post'=>$item->id])}}" class="d-inline-block" >
                                    @csrf
                                    <button class="btn btn-primary ml-2" type ='submit'onclick="return confirm('Back for change something?')">Send </button>

                                </form>
                            </td>--}}
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/category/store.blade.php
@extends('layouts.app')
@section ('content')
    <div class="col-md-8">
        {{--{{Breadcrumbs::render('products',$data->name,'Products')}}--}}

        <div class="card">
            <div class="card-header">Add Category</div>
            <div class="card-body">
                <form method="POST" action="{{route('category.store',['id'=>auth()->user()->id])}}">

                    @csrf
                    <div class="form-group row">
                        <label for="name" class="col-sm-4 col-form-label text-md-right"> Name</label>
                        <div class="col-md-6"><input id="name" type="text" name="name" value="" required="required" autofocus="autofocus" class="form-control"></div>
                    </div>
                    <div class="form-group row">
                        <label for="text" class="col-md-4 col-form-label text-md-right">Category</label>
                        <div class="col-md-6"><textarea id="password"  name="description" required="required" class="form-control"></textarea>
                        </div>
                    </div>
                    <div class="form-group row mt-2"><div class="col-md-8 offset-md-4"><button type="submit" class="btn btn-primary">
                                Add
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


@endsection