routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

    Auth::routes(['verify' => true]);

    Route::group(['middleware'=>['isAdmin','verified'],'prefix'=>'admin','namespace'=>'Admin'],function(){
        Route::get('', 'AdminController@index')->name('admin');
        Route::get('posts/all','PostController@all')->name('posts.all');
        Route::post('posts/move/{post}
        ','PostController@move')->name('posts.move');
        Route::get('category/posts/{id}','CategoryController@posts')->name('category.posts');
       Route::resource('users', 'UserController')->middleware('admin_only');
       Route::resource('posts', 'PostController');
       Route::resource('category', 'CategoryController');
    });
//for user
    Route::group(['middleware'=>['user','verified']],function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::match(['get','post'],'/images', 'HomeController@images')->name('images');
        Route::get('openimage','HomeController@openimage');
        Route::name('cut')->match(['get','post'],'/cut', 'HomeController@cut');
        Route::post('messages','MessageController@index');
        Route::view('/messages', 'user\message');
        Route::post('messages/get','MessageController@getMessage');

    });
    Route::get('posts/{user}', 'PostsForAllController@posts')->name('home.posts');
    Route::post('posts/search', 'PostsForAllController@search')->name('searched.posts');
    Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
    Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
    Route::get('post/{userid}','PostsForAllController@show_post')->name('home.show');
    Route::post('post/store','PostsForAllController@store')->name('home.store');

/*
Route::get('test', function () {
    event(new App\Events\StatusLiked('Someone'));
    return "Event has been sent!";
});*/

resources/views/admin/allPosts.blade.php
@extends('layouts.app')
@section ('content')

    <div class="container">
        <h3 class="text-center">Posts</h3>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <table class="table mt-3 jquery_table"  >
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Post</th>
                        <th>Action</th>
                        <th>Action</th>

                    </tr>
                    </thead>
                    <tbody>

                        @foreach(App\Post::all() as $item)
                            <tr>
                                <td>{{ $item->name}} </td>
                                <td>{{ $item->Post }}</td>
                                <td>

                                    <form method ='GET' action="{{route('posts.edit',['id'=>$item->id])}}"class="d-inline-block" >
                                        @csrf
                                        <button class="btn btn-primary" type ='submit'> Edit</button> </form></td>
                                <td>
                                    <form method ='POST'
                                          action="{{route('posts.destroy',['id'=>$item->id])}}" class="d-inline-block ml-2" onclick="return confirm('Are you sure you want to delete this item?')">
                                        @method('DELETE')
                                        @csrf
                                        <button class="btn btn-primary ml-2" type ='submit'>Delete </button>
                                    </form>
                                </td>
                                {{--<td>
                                    <form method ='POST' action="{{route('posts.move',['post'=>$item->id])}}" class="d-inline-block" >
                                        @csrf
                                        <button class="btn btn-primary ml-2" type ='submit'onclick="return confirm('Back for change something?')">Send </button>

                                    </form>
                                </td>--}}
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    @endsection

resources/views/admin/backedNotifications.blade.php
@extends('layouts.app')
@section ('content')
    <div class="container">
        <h3 class="text-center">Posts</h3>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <table class="table mt-3 jquery_table"  >
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Post</th>
                        <th>Action</th>
                        @role('admin')
                        <th>Back</th>
                        @endrole
                    </tr>
                    </thead>
                    <tbody>

                    @foreach(auth()->user()->Posts()->where('moved',1)->get() as $item)
                        <tr>
                            <td>{{ $item->name}} </td>
                            <td>{{ $item->Post }}</td>
                            <td>
                                 <form method ='GET' action="{{route('posts.edit',['id'=>$item->id])}}"class="d-inline-block" >
                                    @csrf
                                    <button class="btn btn-primary" type ='submit'> Edit</button> </form>
                            </td>
                            <td>
                                @role('admin')
                                <form method ='POST'
                                      action="{{route('posts.destroy',['id'=>$item->id])}}" class="d-inline-block ml-2" onclick="return confirm('Are you sure you want to delete this item?')">
                                    @method('DELETE')
                                    @csrf
                                    <button class="btn btn-primary ml-2" type ='submit'>Delete </button>
                                </form>
                                @endrole

                            </td>
                            @role('admin')
                            <td>
                                <form method ='POST' action="{{route('posts.move',['post'=>$item->id])}}" class="d-inline-block" >
                                    @csrf
                                    <button class="btn btn-primary ml-2" type ='submit' onclick="return confirm('Back for change something?')">Send </button>
                                </form>
                            </td>
                            @endrole
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/edit.blade.php
@extends('layouts.app')
@section ('content')

    <div class="col-md-8">
       {{--{{Breadcrumbs::render('products',$data->name,'Products')}}--}}

        <div class="card">
            <div class="card-header">Change Category</div> <div class="card-body">
                <form method="POST" action="{{route('users.update',$data->id)}}">
                    @method('PUT')
                    @csrf
                    <div class="form-group row">
                        <label for="name" class="col-sm-4 col-form-label text-md-right"> Name</label>
                        <div class="col-md-6"><input id="name" type="text" name="name" value="{{$data->name}}" required="required" autofocus="autofocus" class="form-control"></div>
                    </div>
                    <div class="form-group row">
                        <label for="text" class="col-md-4 col-form-label text-md-right">Email</label>
                        <div class="col-md-6"><textarea id="password"  name="email" required="required" class="form-control">{{$data->email}}</textarea>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-md-8 text-center ">
                            <select name="roles" class="form-control ">
                            <option @if ($data->hasRole('user'))selected="selected" @endif value="user">User</option>
                            <option @if ($data->hasRole('moderator'))selected="selected" @endif value="moderator">Moderator</option>
                            <option @if ($data->hasRole('admin')) selected="selected" @endif value="admin">Admin</option>
                            </select>
                        </div>
                    </div>


                    <div class="form-group row mt-2"><div class="col-md-8 offset-md-4"><button type="submit" class="btn btn-primary">
                                Change
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        You are logged in Admin page!
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/admin/notifications.blade.php
@extends('layouts.app')
@section ('content')
    <div class="container">
        <h3 class="text-center">Posts</h3>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <table class="table mt-3 jquery_table">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Post</th>
                        <th>Action</th>
                        <th>Action</th>
                        @role('admin')
                        <th>Back</th>
                        @endrole
                    </tr>
                    </thead>
                    <tbody>
                    @if(App\Post::where(['confirmed',0]))
                    @foreach(App\Post::where([
                        ['confirmed',0],
                        ['moved',0]
                    ])->get() as $item)
                        <tr>
                            <td>{{ $item->name}} </td>
                            <td>{{ $item->Post  }}</td>
                            <td>
                                <form method ='GET' action="{{route('posts.edit',['id'=>$item->id])}}"class="d-inline-block" >
                                    @csrf
                                    <button class="btn btn-primary" type ='submit'> Edit</button> </form></td>
                            <td>
                                    <form method ='POST'
                                          action="{{route('posts.destroy',['id'=>$item->id])}}" class="d-inline-block" onclick="return confirm('Are you sure you want to delete this item?')">
                                        @method('DELETE')
                                    @csrf
                                    <button class="btn btn-primary ml-2" type ='submit'>Delete </button>
                                    </form>
                            </td>
                            @role('admin')
                            <td>
                                <form method ='POST' action="{{route('posts.move',['post'=>$item->id])}}" class="d-inline-block" >
                                    @csrf
                                    <button class="btn btn-primary ml-2" type ='submit'onclick="return confirm('Back for change something?')">Send </button>
                                </form>
                            </td>
                            @endrole
                        </tr>
                    @endforeach
                    </tbody>
                    @endif
                </table>
        </div>
    </div>
    </div>
    @endsection

resources/views/admin/postedit.blade.php
@extends('layouts.app')
@section ('content')

    <div class="col-md-8">
        {{--{{Breadcrumbs::render('products',$data->name,'Products')}}--}}

        <div class="card container-fluid">
            <div class="card-header row">Change Post</div> <div class="card-body">
                <form method="POST" action="{{route('posts.update',$data->id)}}  ">
                    @method('PUT')
                    @csrf
                    <div class="form-group row">
                        <label for="name" class="col-sm-4 col-form-label text-md-right"> Name</label>
                        <div class="col-md-6"><input id="name" type="text" name="name" value="{{$data->name}}" required="required" autofocus="autofocus" class="form-control"></div>
                    </div>
                    <div class="form-group row">
                        <label for="text" class="col-md-4 col-form-label text-md-right">Post</label>
                        <div class="col-md-6"><textarea id="password"  name="posts" required="required" class="form-control">{{$data->Post}}</textarea>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-md-8 text-center ">

                        </div>
                    </div>


                    <div class="row justify-content-center">
                        <div class="col-md-8 text-center ">
                            <select name="category" class="form-control ">
                                @foreach(App\Category::all() as $item)
                                <option  value="user">{{$item->name}}</option>
                       @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row mt-2"><div class="col-md-8 offset-md-4"><button type="submit" class="btn btn-primary">
                                Change
                            </button>

                        </div>
                    </div>
                </form>
              {{--  @role('admin')
                <form method ='POST' action="{{route('posts.move',['post'=>$data->id])}}" class="text-right" >
                    @csrf
                    <button class="btn btn-primary ml-2 " type ='submit'onclick="return confirm('Back for change something?')">Send </button>
                </form>
                @endrole--}}
            </div>
        </div>
    </div>

@endsection

resources/views/admin/posts.blade.php
@extends('layouts.app')
@section ('content')

    <div class="col-md-8">
        {{--{{Breadcrumbs::render('products',$data->name,'Products')}}--}}

        <div class="card">
            <div class="card-header">Add Post</div> <div class="card-body">
                <form method="POST" action="{{route('posts.store')}} " enctype="multipart/form-data">

                    @csrf
                    <div class="form-group row">
                        <label for="name" class="col-sm-4 col-form-label text-md-right"> Name</label>
                        <div class="col-md-6"><input id="name" type="text" name="name" value="" required="required" autofocus="autofocus" class="form-control"></div>
                    </div>
                    <div class="form-group row">
                        <label for="text" class="col-md-4 col-form-label text-md-right">Post</label>
                        <div class="col-md-6"><textarea id="password"  name="posts" required="required" class="form-control"></textarea>
                        </div>
                    </div>

                    <div class="row ">
                        <label for="name" class="col-md-4 col-form-label text-md-right"> Category</label>
                        <div class="col-md-7 text-center ">
                          {{--  <select name="category[]" multiple   class="form-control ">
                                @foreach(App\Category::all() as $item)
                                    <option  value="{{$item->id}}">{{$item->name}}</option>
                                    @endforeach
                            </select>--}}
                            <select class="js-example-basic-multiple w-75" name="category[]" multiple="multiple">
                                @foreach(App\Category::all() as $item)
                                    <option  value="{{$item->id}}">{{$item->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group row mt-2">
                        <label for="name" class="col-md-4 col-form-label text-md-right"> Upload</label>
                        <div class="col-md-8 ">

                            <input type="file" name="image" class="form-control col-md-8"/>
                        </div>
                    </div>
                     <div class="form-group row mt-2"><div class="col-md-8 offset-md-4"><button type="submit" class="btn btn-primary">
                                Change
                            </button>
                        </div>
                    </div>

                </form>
                @if(isset($errors))
                    @foreach($errors->all() as $error)
                    <div>{{$error}}</div>
                    @endforeach
                @endif
                @if(isset($message))<div>{{$message}}</div>@endif
            </div>
        </div>
    </div>

@endsection

resources/views/admin/users.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <table class="table jquery_table dataTable mt-3" id="table">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach($users as $item)
                        <tr>
                            <td>{{ $item->name}} </td>
                            <td>{{ $item->email }}</td>
                            <td>
                                <form method ='GET' action="{{route('users.edit',['user'=>$item->id])}}" class="d-inline-block">
                                    @csrf
                                    <button class="btn" type ='submit'> Edit</button> </form>
                                <form method ='POST'
                                                                                            action="{{route('users.destroy',['id'=>$item->id])}}" class="d-inline-block" >
                                        @method('DELETE')
                                        @csrf
                                        <button class="btn btn-primary ml-2" type ='submit'onclick="return confirm('Are you sure you want to delete this item?')">Delete </button>
                                    </form>
                                </td>

                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script>
     /*   $(document).ready(function () {
            $('#table').DataTable();
        } );*/
        /*$(document).ready(function () {
         $(document).on('click','.role button',function (){
         $id =$(this).data('id');
         $role =$(this).text();
         var thistag =$(this);
         alert($id );
         $.ajax({
         type: 'GET',
         url: '/change',
         data: {id :$id,role:$role},
         success: function (data) {
         console.log($("[data-get=id]"));
         var id = data[0].id;
         $("[data-get='"+id+"']").text(data[0].role);
         }
         })
         })

         })*/
    </script>

@endsection